trigger:
- clrprofiler

variables:
  Agent.BuildDirectory: 'C:\\'

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: |
    git checkout clrprofiler
    git clone https://github.com/dotnet/coreclr.git $(Agent.BuildDirectory)/coreclr
    powershell ./tools/install-vcpkgs.ps1
    git submodule update --init -- "src/SkyApm.Transport.Grpc.Protocol/protocol" 

    "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat" 

    cd src\SkyAPM.ClrProfiler
    SET BuildArch=x64
    SET BuildType=Debug
    build
  displayName: 'build profiler dll'
